version: '3.6'
services:
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - "SWAGGER_JSON_URL=http://localhost:8078/services.yaml"
    ports:
      - "8079:8080"
    restart: unless-stopped
  helper:
    build: ./image
    ports:
      - "8078:80"
    restart: unless-stopped
